<a href="https://colab.research.google.com/github/AllenGeorge08/NeuralNetworksFromScratch/blob/master/MakemorePart1FromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
path = kagglehub.dataset_download("skaspari/makemore-names")

100%|██████████| 102k/102k [00:00<00:00, 35.8MB/s]

Extracting files...


In [ ]:
words = open(f'{path}/names.txt','r').read().splitlines()
words


['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn',
 'abigail',
 'emily',
 'elizabeth',
 'mila',
 'ella',
 'avery',
 'sofia',
 'camila',
 'aria',
 'scarlett',
 'victoria',
 'madison',
 'luna',
 'grace',
 'chloe',
 'penelope',
 'layla',
 'riley',
 'zoey',
 'nora',
 'lily',
 'eleanor',
 'hannah',
 'lillian',
 'addison',
 'aubrey',
 'ellie',
 'stella',
 'natalie',
 'zoe',
 'leah',
 'hazel',
 'violet',
 'aurora',
 'savannah',
 'audrey',
 'brooklyn',
 'bella',
 'claire',
 'skylar',
 'lucy',
 'paisley',
 'everly',
 'anna',
 'caroline',
 'nova',
 'genesis',
 'emilia',
 'kennedy',
 'samantha',
 'maya',
 'willow',
 'kinsley',
 'naomi',
 'aaliyah',
 'elena',
 'sarah',
 'ariana',
 'allison',
 'gabriella',
 'alice',
 'madelyn',
 'cora',
 'ruby',
 'eva',
 'serenity',
 'autumn',
 'adeline',
 'hailey',
 'gianna',
 'valentina',
 'isla',
 'eliana',
 'quinn',
 'nevaeh',
 'ivy',
 'sadie',
 'piper',
 'lydia',
 'alexa',
 'josephine',
 'emery',
 'julia'

In [ ]:
# Converting chars into numbers bcz pytorch workss with tensors
chars = sorted(set("".join(words)))

# String to integer
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi["."] = 0

# Integer to string
itos = {i:s for s, i in stoi.items()}

vocab_size = len(stoi)

In [ ]:
import torch
N = torch.zeros((vocab_size,vocab_size),dtype=torch.int32) #27x27 matrix of a character mapping
N

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],


In [21]:
print("Building a  simple bigram")
for word in words:
  chars = ["."] + list(word) + ["."]
  for ch1,ch2 in zip(chars,chars[1:]):
    ix1 = stoi[ch1]
    ix2  = stoi[ch2]

    N[ix1,ix2] += 1


N.shape

Building a  simple bigram


torch.Size([27, 27])

In [ ]:
g = torch.Generator().manual_seed(2147483647)
for _ in range(20):
  ix = 0
  output = []

  while True:
      # counts  of possible next characters
      counts = N[ix].float() #Entire row corressponding to N[ix]
      # Convert counts -> probabilities e.g a=100,b=50 whatever..
      probabilities = counts/sum(counts) #It's a prob dist. now..

      # Sample next character (Pick one char acc to the probs in p) /Random sampling..
      ix = torch.multinomial(
          probabilities,
          num_samples=1,
          replacement=True,
          generator=g
      ).item()

      if ix==0: #. means end of name..
        break

      output.append(itos[ix]) #append the




  print("".join(output))

cexze
momasurailezitynn
konimittain
llayn
ka
da
staiyaubrtthrigotai
moliellavo
ke
teda
ka
emimmsade
enkaviyny
ftlspihinivenvorhlasu
dsor
br
jol
pen
aisan
ja


In [ ]:
# Neural Bigram Model
import torch
import torch.nn.functional as F

# Create training examples
xs = []
ys = []

for word in words:
  chars = ["."] + list(word) + ["."]

  for ch1,ch2 in zip(chars,chars[1:]):
    xs.append(stoi[ch1]) #current character
    ys.append(stoi[ch2]) #next character


xs = torch.tensor(xs)
ys  = torch.tensor(ys)

print(xs.shape)
print(ys.shape)

torch.Size([228146])
torch.Size([228146])


In [23]:
# Initializign the weights/model..

g = torch.Generator().manual_seed(2147483647)

# This iss where we will store weights, random values nxn
W = torch.randn(
    (27,27),
    generator=g,
    requires_grad=True
)

tensor([[ 1.5674e+00, -2.3729e-01, -2.7385e-02, -1.1008e+00,  2.8588e-01,
         -2.9643e-02, -1.5471e+00,  6.0489e-01,  7.9136e-02,  9.0462e-01,
         -4.7125e-01,  7.8682e-01, -3.2843e-01, -4.3297e-01,  1.3729e+00,
          2.9334e+00,  1.5618e+00, -1.6261e+00,  6.7716e-01, -8.4039e-01,
          9.8488e-01, -1.4837e-01, -1.4795e+00,  4.4830e-01, -7.0730e-02,
          2.4968e+00,  2.4448e+00],
        [-6.7006e-01, -1.2199e+00,  3.0314e-01, -1.0725e+00,  7.2762e-01,
          5.1114e-02,  1.3095e+00, -8.0220e-01, -8.5042e-01, -1.8068e+00,
          1.2523e+00, -1.2256e+00,  1.2165e+00, -9.6478e-01, -2.3211e-01,
         -3.4762e-01,  3.3244e-01, -1.3263e+00,  1.1224e+00,  5.9641e-01,
          4.5846e-01,  5.4011e-02, -1.7400e+00,  1.1560e-01,  8.0319e-01,
          5.4108e-01, -1.1646e+00],
        [ 1.4756e-01, -1.0006e+00,  3.8012e-01,  4.7328e-01, -9.1027e-01,
         -7.8305e-01,  1.3506e-01, -2.1161e-01, -1.0406e+00, -1.5367e+00,
          9.3743e-01, -8.8303e-01,  1.74

In [29]:
for step in range(100):
   # Forward pass
   xenc = F.one_hot(xs,num_classes=27).float() #input features , xenc = (number of examples,27) ..W=(27,27)
   logits  = xenc@W #(logits=(number_of_examples,27))
  #  we get [2.0,1.0,0.0]..thesse are prob

  #  Softmax (turn into valid prob bw 0 and 1), which sum to 1
   counts = logits.exp()  #exp does-> large number = much larger +ve number, smaller sscore-> smaller number..
   probs = counts/counts.sum(dim=1,keepdim=True)

  #Negative log likelihood

  # High prob for correct answer -> small NLL. ..
  # lOW prob for correct answer -> large NLL...
   correct_probs = probs[torch.arange(len(xs)),ys] #How good was the probability the model assigned to the correct answer?
  #  e.g p(m|a) = 0.8, then -log(0.8) = 0.223 small loss, but if 0.1 it gives 2.303

    # we want mean -ve log likelihood, and that's what we're using ass our training loss
   nll = -correct_probs.log().mean()  #we want a +ve loss

  #  L2 Regularization
   reg = 0.01*(W**2).mean()

   loss = nll+reg

  #  Backward pass
   W.grad = None
   loss.backward()

    # Gradient descent/loss update
   W.data += -0.1*W.grad
   print(f"Step : {step}: loss={loss.item():.4f}")


Step : 0: loss=2.7436
Step : 1: loss=2.7435
Step : 2: loss=2.7435
Step : 3: loss=2.7434
Step : 4: loss=2.7434
Step : 5: loss=2.7433
Step : 6: loss=2.7433
Step : 7: loss=2.7432
Step : 8: loss=2.7431
Step : 9: loss=2.7431
Step : 10: loss=2.7430
Step : 11: loss=2.7430
Step : 12: loss=2.7429
Step : 13: loss=2.7429
Step : 14: loss=2.7428
Step : 15: loss=2.7427
Step : 16: loss=2.7427
Step : 17: loss=2.7426
Step : 18: loss=2.7426
Step : 19: loss=2.7425
Step : 20: loss=2.7425
Step : 21: loss=2.7424
Step : 22: loss=2.7424
Step : 23: loss=2.7423
Step : 24: loss=2.7422
Step : 25: loss=2.7422
Step : 26: loss=2.7421
Step : 27: loss=2.7421
Step : 28: loss=2.7420
Step : 29: loss=2.7420
Step : 30: loss=2.7419
Step : 31: loss=2.7419
Step : 32: loss=2.7418
Step : 33: loss=2.7417
Step : 34: loss=2.7417
Step : 35: loss=2.7416
Step : 36: loss=2.7416
Step : 37: loss=2.7415
Step : 38: loss=2.7415
Step : 39: loss=2.7414
Step : 40: loss=2.7413
Step : 41: loss=2.7413
Step : 42: loss=2.7412
Step : 43: loss=2.741

In [30]:
# GENERATING NAMES:
for _ in range(10):
  ix = 0
  output  = []

  while True:
    # Current character -> one hot
    x = F.one_hot(torch.tensor([ix]),num_classes=27).float()

    # Neural network
    logits = x@W

    # Softmax
    probs = F.softmax(logits,dim=1) #Softmax is the function that takes the model's raw scores (logits) and turns them into probabilities that add up to 1...[2.0, 1.0, 0.0]# ↓ softmax # [0.665, 0.245, 0.090]

    # Sample next char
    ix = torch.multinomial(probs,num_samples=1,replacement=True,generator=g).item()

    # End
    if ix==0:
      break

    output.append(itos[ix])

  print("".join(output))

kfjan
kaedeshahtrzgaybl
dayli
kotjasihqzqrzw
eie
ke
s
s

gvolyvitn


In [ ]:
  # x = F.one_hot(torch.tensor([5]),num_classes=27).float()
  # x

tensor([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])